
POST http://localhost:5000/api/url/shorten
Content-Type: application/json

{
    "longUrl" : "https://www.amazon.in/Harry-Potter-Goblet-Fire-Rowling-ebook/dp/B019PIOJWW/ref=zg_ebk_9?_encoding=UTF8&pd_rd_i=B019PIOJWW&pd_rd_r=dec03f27-4ca3-47b1-9b35-f5af085bdb98&pd_rd_w=qzbqq&pd_rd_wg=Jnc4E&pf_rd_p=921c46ba-60b0-407a-9757-760ea2497c1b&pf_rd_r=5BVA2C5QMMDPC1VG3DFT&psc=1&refRID=5BVA2C5QMMDPC1VG3DFT"
}
